"""
Router QoS & SQM Advisor for Network Stabilizer.
Provides manual guidance, 85%/90%/93% shaping calculations, and OpenWrt CAKE templates.
Never connects to or alters router hardware remotely.
"""

from typing import Dict, Any, Optional


class RouterAdvisor:
    """
    Expert advisor for home router Smart Queue Management (SQM) and bufferbloat mitigation.
    Manual guidance only — outside the application's rollback system.
    """

    SUPPORTED_FIRMWARES = [
        "OpenWrt (CAKE / fq_codel)",
        "Asuswrt-Merlin (Adaptive QoS / fq_codel)",
        "TP-Link (HomeCare / HomeShield QoS)",
        "Netgear (Dynamic QoS / DumaOS)",
        "Ubiquiti UniFi (Smart Queues)",
        "Eero (SQM / Optimize for Gaming)",
        "Generic Consumer Router"
    ]

    CONNECTION_TYPES = [
        "Cable / DOCSIS (Asymmetric, prone to bufferbloat)",
        "Fiber (FTTH, Low base jitter)",
        "DSL / VDSL (High framing overhead)",
        "5G / 4G LTE Fixed Wireless"
    ]

    @staticmethod
    def calculate_shaping_tiers(down_mbps: float, up_mbps: float) -> Dict[str, Any]:
        """
        Calculates 85%, 90%, and 93% shaping rates for download and upload.
        """
        down_mbps = max(1.0, float(down_mbps))
        up_mbps = max(0.5, float(up_mbps))

        return {
            "tier_85": {
                "pct": 85,
                "down_mbps": round(down_mbps * 0.85, 1),
                "up_mbps": round(up_mbps * 0.85, 1),
                "down_kbps": int(down_mbps * 0.85 * 1000),
                "up_kbps": int(up_mbps * 0.85 * 1000),
                "recommendation": "Recommended for Cable / DOCSIS and DSL connections with severe bufferbloat."
            },
            "tier_90": {
                "pct": 90,
                "down_mbps": round(down_mbps * 0.90, 1),
                "up_mbps": round(up_mbps * 0.90, 1),
                "down_kbps": int(down_mbps * 0.90 * 1000),
                "up_kbps": int(up_mbps * 0.90 * 1000),
                "recommendation": "Standard balanced SQM ceiling for most broadband connections."
            },
            "tier_93": {
                "pct": 93,
                "down_mbps": round(down_mbps * 0.93, 1),
                "up_mbps": round(up_mbps * 0.93, 1),
                "down_kbps": int(down_mbps * 0.93 * 1000),
                "up_kbps": int(up_mbps * 0.93 * 1000),
                "recommendation": "Recommended for high-capacity symmetric Fiber (FTTH) lines with low base jitter."
            }
        }

    @staticmethod
    def calculate_bandwidth_limits(down_mbps: float, up_mbps: float, conn_type: str = "Cable") -> Dict[str, Any]:
        """
        Convenience method for router bandwidth ceiling calculations.
        Returns 88% down / 85% up for cable, or custom tier calculations.
        """
        tiers = RouterAdvisor.calculate_shaping_tiers(down_mbps, up_mbps)
        down_lim = round(down_mbps * 0.88, 1)
        up_lim = round(up_mbps * 0.85, 1)
        return {
            "down_limit_mbps": down_lim,
            "up_limit_mbps": up_lim,
            "down_ratio_pct": 88,
            "up_ratio_pct": 85,
            "tiers": tiers
        }

    @staticmethod
    def generate_openwrt_config(
        down_kbps: int,
        up_kbps: int,
        wan_iface: Optional[str] = None,
        qdisc: str = "cake",
        script: str = "layer_cake.qos"
    ) -> str:
        """
        Generates production-grade OpenWrt /etc/config/sqm block.
        Uses <CONFIRM_WAN_INTERFACE> placeholder unless confirmed by user.
        """
        iface = wan_iface.strip() if wan_iface and wan_iface.strip() else "<CONFIRM_WAN_INTERFACE>"

        return f"""# =======================================================
# OpenWrt SQM Configuration: /etc/config/sqm
# Generated by Network Stabilizer (Manual Guidance)
# =======================================================

config queue '{iface}'
    option enabled '1'
    option interface '{iface}'
    option download '{down_kbps}'
    option upload '{up_kbps}'
    option qdisc '{qdisc}'
    option script '{script}'
    option linklayer 'none'
    option overhead '0'
    option qdisc_really_really_advanced '1'
    option qdisc_advanced_options 'diffserv4'

# --- Essential Educational Notes ---
# 1. SQM must be configured on your WAN (Internet-facing) interface.
#    Verify your real WAN interface in Network -> Interfaces (often 'wan', 'eth1', or 'pppoe-wan').
# 2. CAKE (Common Applications Kept Enhanced) actively manages buffer queues to reduce latency spikes.
# 3. CPU Impact: SQM performs per-packet shaping which consumes router CPU.
# 4. Offloading Conflict: In Network -> Firewall, ensure 'Software flow offloading' and
#    'Hardware flow offloading' are DISABLED, as offloading bypasses SQM traffic shaping!
# 5. Router modifications are manual and outside this software's rollback system.
"""

    @staticmethod
    def get_router_guide(
        firmware: str,
        down_mbps: float,
        up_mbps: float,
        conn_type: str = "Cable",
        wan_iface: Optional[str] = None
    ) -> Dict[str, Any]:
        """Returns structured guidance and instructions tailored to selected router."""
        tiers = RouterAdvisor.calculate_shaping_tiers(down_mbps, up_mbps)

        # Select recommended tier based on connection type
        conn_str = conn_type if isinstance(conn_type, str) else "Cable"
        if "Fiber" in conn_str:
            active_tier = tiers["tier_93"]
        elif "DSL" in conn_str or "5G" in conn_str:
            active_tier = tiers["tier_85"]
        else:
            active_tier = tiers["tier_90"]

        d_k = active_tier["down_kbps"]
        u_k = active_tier["up_kbps"]
        d_m = active_tier["down_mbps"]
        u_m = active_tier["up_mbps"]

        if "OpenWrt" in firmware:
            return {
                "title": "OpenWrt Smart Queue Management (CAKE)",
                "recommended_qdisc": "CAKE (layer_cake.qos)",
                "tiers": tiers,
                "active_tier": active_tier,
                "steps": [
                    "Open your router web portal (usually http://192.168.1.1).",
                    "Navigate to Network -> Interfaces and identify your WAN interface name (e.g. 'wan' or 'eth1').",
                    "Navigate to Network -> SQM QoS and check 'Enable this SQM instance'.",
                    f"Replace '<CONFIRM_WAN_INTERFACE>' with your confirmed WAN interface name.",
                    f"Set Download Speed: {d_k} kbps ({d_m} Mbps) and Upload Speed: {u_k} kbps ({u_m} Mbps).",
                    "Under 'Queue Discipline': Select qdisc = 'cake' and setup script = 'layer_cake.qos'.",
                    "Under 'Network -> Firewall -> Routing/NAT': Disable Software & Hardware Flow Offloading.",
                    "Save & Apply. Re-test with the Diagnostics probe to verify reduced latency under load."
                ],
                "snippet": RouterAdvisor.generate_openwrt_config(d_k, u_k, wan_iface=wan_iface)
            }
        elif "Asuswrt" in firmware:
            return {
                "title": "Asuswrt-Merlin Adaptive QoS (fq_codel)",
                "recommended_qdisc": "fq_codel (Manual Bandwidth)",
                "tiers": tiers,
                "active_tier": active_tier,
                "steps": [
                    "Log into your ASUS router portal (http://router.asus.com or 192.168.1.1).",
                    "Click 'Adaptive QoS' -> 'QoS'.",
                    "Set 'Enable QoS' to ON and choose 'Manual Bandwidth' (or Adaptive QoS with Gaming prioritized).",
                    f"Set Download Limit: {d_m} Mbps ({active_tier['pct']}% of line rate).",
                    f"Set Upload Limit: {u_m} Mbps ({active_tier['pct']}% of line rate).",
                    "In Asuswrt-Merlin, choose Queue Discipline: 'fq_codel'.",
                    "Apply changes and test latency."
                ],
                "snippet": f"ASUS QoS Configuration:\nDownload Rate: {d_m} Mbps\nUpload Rate: {u_m} Mbps\nDiscipline: fq_codel\nPriority: Gaming"
            }
        else:
            return {
                "title": f"{firmware} QoS Setup",
                "recommended_qdisc": "Priority Bandwidth Limiter",
                "tiers": tiers,
                "active_tier": active_tier,
                "steps": [
                    "Access your router admin dashboard at your Default Gateway (e.g. 192.168.1.1).",
                    "Locate 'QoS', 'Traffic Control', or 'Bandwidth Management'.",
                    f"Set Maximum Ingress / Download to: {d_m} Mbps ({active_tier['pct']}%).",
                    f"Set Maximum Egress / Upload to: {u_m} Mbps ({active_tier['pct']}%).",
                    "Assign your gaming PC's IP or MAC address to 'Highest Priority'.",
                    "Save settings."
                ],
                "snippet": f"Router Bandwidth Settings:\nDownload Cap: {d_m} Mbps ({active_tier['pct']}%)\nUpload Cap: {u_m} Mbps ({active_tier['pct']}%)\nTarget PC: High Priority"
            }
